name = "aftk"
version = "0.1.0"
defaultTargets = ["aftk"]

[[require]]
name = "lean_worker"
git = "https://github.com/adamtopaz/lean_worker"
rev = "main"

[[lean_exe]]
name = "file_worker"
root = "AFTK.FileWorker"
supportInterpreter = true

[[lean_lib]]
name = "AFTK"

[[lean_exe]]
name = "aftk"
root = "Main"
