import Lake

open System Lake DSL

package aftk where
  testDriver := "aftk_test"
  version := v!"0.1.0"

require lean_worker from git "https://github.com/adamtopaz/lean_worker"@"main"

lean_lib AFTK

lean_lib AFTKTest

@[default_target] lean_exe aftk where
  root := `Main
  supportInterpreter := true

lean_exe aftk_server where
  root := `AFTK.Server.Main
  supportInterpreter := true

lean_exe aftk_file_worker where
  root := `AFTK.FileWorker.Main
  supportInterpreter := true

lean_exe aftk_knowledgebase_test where
  root := `AFTKTest.KnowledgeBase.Main
  supportInterpreter := true

lean_exe aftk_informal_test where
  root := `AFTKTest.Informal.Main
  supportInterpreter := true

lean_exe aftk_server_test where
  root := `AFTKTest.Server.Main
  supportInterpreter := true

lean_exe aftk_test where
  root := `AFTKTest.Main
  supportInterpreter := true

private def generatedByLine : String :=
  "Generated by `lake run aftk_setup`. Re-run to refresh."

private def shimHeader : String :=
  s!"// {generatedByLine}"

private def promptHeader : String :=
  s!"<!-- {generatedByLine} -->"

private def usageText : String :=
  String.intercalate "\n" [
    "Usage:",
    "  lake run aftk_setup",
    "  lake run aftk_setup --help"
  ]

private def helpText : String :=
  String.intercalate "\n\n" [
    usageText,
    "Create or refresh the project-local pi extension shim and appended system prompt for AFTK.",
    String.intercalate "\n" [
      "This command writes:",
      "- .pi/extensions/aftk-toolkit.ts",
      "- .pi/APPEND_SYSTEM.md"
    ],
    "It is safe to rerun. Existing files are updated only when they match the generated-file marker."
  ]

private def dropLeadingEmptyParts : List String → List String
  | "" :: rest => dropLeadingEmptyParts rest
  | rest => rest

private def commonPrefixLength : List String → List String → Nat
  | left :: leftRest, right :: rightRest =>
      if left == right then
        commonPrefixLength leftRest rightRest + 1
      else
        0
  | _, _ => 0

private structure PathPieces where
  root? : Option String
  parts : List String

private def looksLikeWindowsDrive (part : String) : Bool :=
  part.length == 2 && part.drop 1 == ":"

private def pathPieces (path : FilePath) : PathPieces :=
  let normalized := path.normalize
  let parts := normalized.components
  if normalized.isAbsolute then
    if System.Platform.isWindows then
      match parts with
      | drive :: rest =>
          if looksLikeWindowsDrive drive then
            { root? := some drive, parts := rest }
          else
            { root? := some (String.singleton FilePath.pathSeparator), parts := dropLeadingEmptyParts parts }
      | [] =>
          { root? := some (String.singleton FilePath.pathSeparator), parts := [] }
    else
      { root? := some "/", parts := dropLeadingEmptyParts parts }
  else
    { root? := none, parts := parts }

private def importPathText (path : FilePath) : String :=
  if System.Platform.isWindows then
    path.normalize.toString.map fun c => if c = '\\' then '/' else c
  else
    path.normalize.toString

private def absoluteImportSpecifier (path : FilePath) : String :=
  let text := importPathText path
  if path.isAbsolute then
    if System.Platform.isWindows then s!"file:///{text}" else s!"file://{text}"
  else if text.startsWith "." then
    text
  else
    s!"./{text}"

private def relativeImportSpecifier? (fromDir targetPath : FilePath) : Option String :=
  let fromPieces := pathPieces fromDir
  let destPieces := pathPieces targetPath
  if fromPieces.root? != destPieces.root? then
    none
  else
    let common := commonPrefixLength fromPieces.parts destPieces.parts
    let upParts := List.replicate (fromPieces.parts.length - common) ".."
    let downParts := destPieces.parts.drop common
    let relParts := upParts ++ downParts
    let relPath := mkFilePath relParts
    let relText := Lake.mkRelPathString relPath
    if relText.isEmpty then
      some "./"
    else if relText.startsWith "." then
      some relText
    else
      some s!"./{relText}"

private def computeImportSpecifier (fromFile targetPath : FilePath) : String :=
  match fromFile.parent with
  | some fromDir =>
      (relativeImportSpecifier? fromDir targetPath).getD (absoluteImportSpecifier targetPath)
  | none =>
      absoluteImportSpecifier targetPath

private def buildShimContent (importSpecifier : String) : String :=
  String.intercalate "\n" [
    shimHeader,
    "export { default } from \"" ++ importSpecifier ++ "\";",
    ""
  ]

private def buildPromptContent : String :=
  String.intercalate "\n" [
    promptHeader,
    "# AFTK agent guidance",
    "",
    "This project has the AFTK pi extension enabled. Use AFTK tools to inspect Lean state and project knowledge before guessing.",
    "",
    "## Available tool families",
    "",
    "- Lean/server tools: open Lean files, inspect hover/goals/term goals/infoview, load tactic nodes, and run transient tactic exploration.",
    "- Knowledge-base tools: inspect, search, validate, and relate knowledge-base nodes.",
    "- Informal tools: inspect tracked declarations/references/dependencies and render knowledge-base-backed presentation.",
    "",
    "## Autoformalization workflow",
    "",
    "1. Inspect the current Lean file, local goal state, and nearby informal context before proposing edits.",
    "2. Use knowledge-base and informal tools to understand the target node, related notes, and tracked declarations.",
    "3. Use Lean/server tools to inspect the exact formal state at the relevant source location.",
    "4. Use tactic exploration tools transiently to test candidate proof steps.",
    "5. Turn a successful branch into real Lean source edits and re-check the file.",
    "6. Iterate from the updated checked file state.",
    "",
    "## Safety rules",
    "",
    "- `load_node`, `run_tactic`, and `run_tactic_steps` operate on transient tactic-state nodes, not persisted proof edits.",
    "- Do not treat a successful transient tactic branch as committed proof text until you write it into Lean source and re-check.",
    "- Canonical prose and metadata live in the knowledge base.",
    "- The informal layer is the Lean-facing bridge to that knowledge.",
    "- Prefer inspecting actual AFTK state through tools over inventing assumptions.",
    ""
  ]

private inductive ManagedWritePlan where
  | create
  | overwrite
  | unchanged

private def classifyManagedWrite (path : FilePath) (content marker : String) : IO ManagedWritePlan := do
  if !(← path.pathExists) then
    return .create
  let current ← IO.FS.readFile path
  if current == content then
    return .unchanged
  if current.startsWith marker then
    return .overwrite
  throw <| IO.userError s!"Refusing to overwrite existing user-managed file: {path}"

private def applyManagedWrite (path : FilePath) (content : String) (plan : ManagedWritePlan) : IO Unit := do
  match plan with
  | .unchanged =>
      pure ()
  | .create | .overwrite =>
      Lake.createParentDirs path
      IO.FS.writeFile path content

private def actionLabel (plan : ManagedWritePlan) : String :=
  match plan with
  | .create => "installed"
  | .overwrite => "updated"
  | .unchanged => "already up to date"

private structure SetupSummary where
  projectDir : FilePath
  aftkDir : FilePath
  entryFile : FilePath
  shimPath : FilePath
  promptPath : FilePath
  importSpecifier : String
  shimPlan : ManagedWritePlan
  promptPlan : ManagedWritePlan

private def runAftkSetup : ScriptM SetupSummary := do
  let ws ← getWorkspace
  let projectDir := ws.dir
  let some aftkPkg ← findPackageByName? `aftk
    | throw <| IO.userError "AFTK setup failed: package `aftk` was not found in the current Lake workspace."
  let entryFile := aftkPkg.dir / "src" / "hosts" / "pi" / "extension.ts"
  unless (← entryFile.pathExists) do
    throw <| IO.userError s!"AFTK setup failed: expected pi extension entrypoint is missing: {entryFile}"
  let shimPath := projectDir / ".pi" / "extensions" / "aftk-toolkit.ts"
  let promptPath := projectDir / ".pi" / "APPEND_SYSTEM.md"
  let importSpecifier := computeImportSpecifier shimPath entryFile
  let shimContent := buildShimContent importSpecifier
  let promptContent := buildPromptContent
  let shimPlan ← classifyManagedWrite shimPath shimContent shimHeader
  let promptPlan ← classifyManagedWrite promptPath promptContent promptHeader
  applyManagedWrite shimPath shimContent shimPlan
  applyManagedWrite promptPath promptContent promptPlan
  return {
    projectDir,
    aftkDir := aftkPkg.dir,
    entryFile,
    shimPath,
    promptPath,
    importSpecifier,
    shimPlan,
    promptPlan,
  }

script aftk_setup (args) do
  match args with
  | [] =>
      try
        let summary ← runAftkSetup
        IO.println s!"Workspace root: {summary.projectDir}"
        IO.println s!"AFTK package: {summary.aftkDir}"
        IO.println s!"AFTK pi entrypoint: {summary.entryFile}"
        IO.println s!"AFTK pi extension {actionLabel summary.shimPlan}: {summary.shimPath}"
        IO.println s!"AFTK appended system prompt {actionLabel summary.promptPlan}: {summary.promptPath}"
        IO.println s!"Shim import specifier: {summary.importSpecifier}"
        IO.println "If pi is already running, use `/reload`."
        pure 0
      catch e =>
        IO.eprintln e.toString
        pure 1
  | ["--help"] | ["-h"] =>
      IO.println helpText
      pure 0
  | _ =>
      IO.eprintln usageText
      pure 2
