import Lake

open System Lake DSL

package aftk where
  testDriver := "aftk_test"
  version := v!"0.1.0"

require lean_worker from git "https://github.com/adamtopaz/lean_worker"@"main"

lean_lib AFTK

lean_lib AFTKTest

@[default_target] lean_exe aftk where
  root := `Main
  supportInterpreter := true

lean_exe aftk_server where
  root := `AFTK.Server.Main
  supportInterpreter := true

lean_exe aftk_file_worker where
  root := `AFTK.FileWorker.Main
  supportInterpreter := true

lean_exe aftk_knowledgebase_test where
  root := `AFTKTest.KnowledgeBase.Main
  supportInterpreter := true

lean_exe aftk_informal_test where
  root := `AFTKTest.Informal.Main
  supportInterpreter := true

lean_exe aftk_server_test where
  root := `AFTKTest.Server.Main
  supportInterpreter := true

lean_exe aftk_test where
  root := `AFTKTest.Main
  supportInterpreter := true

private def generatedByLine : String :=
  "Generated by `lake run aftk_setup`. Re-run to refresh."

private def shimHeader : String :=
  s!"// {generatedByLine}"

private def promptHeader : String :=
  s!"<!-- {generatedByLine} -->"

private def toolkitEntryRelativePath : FilePath :=
  mkFilePath ["src", "hosts", "pi", "extension.ts"]

private def loggingEntryRelativePath : FilePath :=
  mkFilePath ["src", "hosts", "pi", "logging-extension.ts"]

private def promptSourceRelativePath : FilePath :=
  mkFilePath ["src", "hosts", "pi", "APPEND_SYSTEM.template.md"]

private def usageText : String :=
  String.intercalate "\n" [
    "Usage:",
    "  lake run aftk_setup",
    "  lake run aftk_setup --help"
  ]

private def helpText : String :=
  String.intercalate "\n\n" [
    usageText,
    "Create or refresh the project-local pi extension shims and appended system prompt for AFTK.",
    String.intercalate "\n" [
      "This command reads from the resolved `aftk` package:",
      "- src/hosts/pi/extension.ts",
      "- src/hosts/pi/logging-extension.ts",
      "- src/hosts/pi/APPEND_SYSTEM.template.md"
    ],
    String.intercalate "\n" [
      "This command writes:",
      "- .pi/extensions/aftk-toolkit.ts",
      "- .pi/extensions/aftk-logging.ts",
      "- .pi/APPEND_SYSTEM.md"
    ],
    "It is safe to rerun. Existing files are updated only when they match the generated-file marker."
  ]

private def dropLeadingEmptyParts : List String → List String
  | "" :: rest => dropLeadingEmptyParts rest
  | rest => rest

private def commonPrefixLength : List String → List String → Nat
  | left :: leftRest, right :: rightRest =>
      if left == right then
        commonPrefixLength leftRest rightRest + 1
      else
        0
  | _, _ => 0

private structure PathPieces where
  root? : Option String
  parts : List String

private def looksLikeWindowsDrive (part : String) : Bool :=
  part.length == 2 && part.drop 1 == ":"

private def pathPieces (path : FilePath) : PathPieces :=
  let normalized := path.normalize
  let parts := normalized.components
  if normalized.isAbsolute then
    if System.Platform.isWindows then
      match parts with
      | drive :: rest =>
          if looksLikeWindowsDrive drive then
            { root? := some drive, parts := rest }
          else
            { root? := some (String.singleton FilePath.pathSeparator), parts := dropLeadingEmptyParts parts }
      | [] =>
          { root? := some (String.singleton FilePath.pathSeparator), parts := [] }
    else
      { root? := some "/", parts := dropLeadingEmptyParts parts }
  else
    { root? := none, parts := parts }

private def importPathText (path : FilePath) : String :=
  if System.Platform.isWindows then
    path.normalize.toString.map fun c => if c = '\\' then '/' else c
  else
    path.normalize.toString

private def absoluteImportSpecifier (path : FilePath) : String :=
  let text := importPathText path
  if path.isAbsolute then
    if System.Platform.isWindows then s!"file:///{text}" else s!"file://{text}"
  else if text.startsWith "." then
    text
  else
    s!"./{text}"

private def relativeImportSpecifier? (fromDir targetPath : FilePath) : Option String :=
  let fromPieces := pathPieces fromDir
  let destPieces := pathPieces targetPath
  if fromPieces.root? != destPieces.root? then
    none
  else
    let common := commonPrefixLength fromPieces.parts destPieces.parts
    let upParts := List.replicate (fromPieces.parts.length - common) ".."
    let downParts := destPieces.parts.drop common
    let relParts := upParts ++ downParts
    let relPath := mkFilePath relParts
    let relText := Lake.mkRelPathString relPath
    if relText.isEmpty then
      some "./"
    else if relText.startsWith "." then
      some relText
    else
      some s!"./{relText}"

private def computeImportSpecifier (fromFile targetPath : FilePath) : String :=
  match fromFile.parent with
  | some fromDir =>
      (relativeImportSpecifier? fromDir targetPath).getD (absoluteImportSpecifier targetPath)
  | none =>
      absoluteImportSpecifier targetPath

private def buildShimContent (importSpecifier : String) : String :=
  String.intercalate "\n" [
    shimHeader,
    "export { default } from \"" ++ importSpecifier ++ "\";",
    ""
  ]

private def promptTemplatePath (aftkDir : FilePath) : FilePath :=
  aftkDir / promptSourceRelativePath

private def buildPromptContent (sourcePath : FilePath) : IO String := do
  unless (← sourcePath.pathExists) do
    throw <| IO.userError s!"AFTK setup failed: expected appended system prompt template is missing: {sourcePath}"
  let body ← IO.FS.readFile sourcePath
  return promptHeader ++ "\n" ++ body

private inductive ManagedWritePlan where
  | create
  | overwrite
  | unchanged

private def classifyManagedWrite (path : FilePath) (content marker : String) : IO ManagedWritePlan := do
  if !(← path.pathExists) then
    return .create
  let current ← IO.FS.readFile path
  if current == content then
    return .unchanged
  if current.startsWith marker then
    return .overwrite
  throw <| IO.userError s!"Refusing to overwrite existing user-managed file: {path}"

private def applyManagedWrite (path : FilePath) (content : String) (plan : ManagedWritePlan) : IO Unit := do
  match plan with
  | .unchanged =>
      pure ()
  | .create | .overwrite =>
      Lake.createParentDirs path
      IO.FS.writeFile path content

private def actionLabel (plan : ManagedWritePlan) : String :=
  match plan with
  | .create => "installed"
  | .overwrite => "updated"
  | .unchanged => "already up to date"

private structure SetupSummary where
  projectDir : FilePath
  aftkDir : FilePath
  toolkitEntryFile : FilePath
  loggingEntryFile : FilePath
  promptSourcePath : FilePath
  toolkitShimPath : FilePath
  loggingShimPath : FilePath
  promptPath : FilePath
  toolkitImportSpecifier : String
  loggingImportSpecifier : String
  toolkitShimPlan : ManagedWritePlan
  loggingShimPlan : ManagedWritePlan
  promptPlan : ManagedWritePlan

private def runAftkSetup : ScriptM SetupSummary := do
  let ws ← getWorkspace
  let projectDir := ws.dir
  let some aftkPkg ← findPackageByName? `aftk
    | throw <| IO.userError "AFTK setup failed: package `aftk` was not found in the current Lake workspace."
  let toolkitEntryFile := aftkPkg.dir / toolkitEntryRelativePath
  unless (← toolkitEntryFile.pathExists) do
    throw <| IO.userError s!"AFTK setup failed: expected pi toolkit extension entrypoint is missing: {toolkitEntryFile}"
  let loggingEntryFile := aftkPkg.dir / loggingEntryRelativePath
  unless (← loggingEntryFile.pathExists) do
    throw <| IO.userError s!"AFTK setup failed: expected pi logging extension entrypoint is missing: {loggingEntryFile}"
  let promptSourcePath := promptTemplatePath aftkPkg.dir
  let toolkitShimPath := projectDir / ".pi" / "extensions" / "aftk-toolkit.ts"
  let loggingShimPath := projectDir / ".pi" / "extensions" / "aftk-logging.ts"
  let promptPath := projectDir / ".pi" / "APPEND_SYSTEM.md"
  let toolkitImportSpecifier := computeImportSpecifier toolkitShimPath toolkitEntryFile
  let loggingImportSpecifier := computeImportSpecifier loggingShimPath loggingEntryFile
  let toolkitShimContent := buildShimContent toolkitImportSpecifier
  let loggingShimContent := buildShimContent loggingImportSpecifier
  let promptContent ← buildPromptContent promptSourcePath
  let toolkitShimPlan ← classifyManagedWrite toolkitShimPath toolkitShimContent shimHeader
  let loggingShimPlan ← classifyManagedWrite loggingShimPath loggingShimContent shimHeader
  let promptPlan ← classifyManagedWrite promptPath promptContent promptHeader
  applyManagedWrite toolkitShimPath toolkitShimContent toolkitShimPlan
  applyManagedWrite loggingShimPath loggingShimContent loggingShimPlan
  applyManagedWrite promptPath promptContent promptPlan
  return {
    projectDir,
    aftkDir := aftkPkg.dir,
    toolkitEntryFile,
    loggingEntryFile,
    promptSourcePath,
    toolkitShimPath,
    loggingShimPath,
    promptPath,
    toolkitImportSpecifier,
    loggingImportSpecifier,
    toolkitShimPlan,
    loggingShimPlan,
    promptPlan,
  }

script aftk_setup (args) do
  match args with
  | [] =>
      try
        let summary ← runAftkSetup
        IO.println s!"Workspace root: {summary.projectDir}"
        IO.println s!"AFTK package: {summary.aftkDir}"
        IO.println s!"AFTK pi toolkit entrypoint: {summary.toolkitEntryFile}"
        IO.println s!"AFTK pi logging entrypoint: {summary.loggingEntryFile}"
        IO.println s!"AFTK prompt template: {summary.promptSourcePath}"
        IO.println s!"AFTK pi toolkit shim {actionLabel summary.toolkitShimPlan}: {summary.toolkitShimPath}"
        IO.println s!"AFTK pi logging shim {actionLabel summary.loggingShimPlan}: {summary.loggingShimPath}"
        IO.println s!"AFTK appended system prompt {actionLabel summary.promptPlan}: {summary.promptPath}"
        IO.println s!"Toolkit shim import specifier: {summary.toolkitImportSpecifier}"
        IO.println s!"Logging shim import specifier: {summary.loggingImportSpecifier}"
        IO.println "If pi is already running, use `/reload`."
        pure 0
      catch e =>
        IO.eprintln e.toString
        pure 1
  | ["--help"] | ["-h"] =>
      IO.println helpText
      pure 0
  | _ =>
      IO.eprintln usageText
      pure 2

private def autoformalizeLoopPromptRelativePath : FilePath :=
  mkFilePath ["src", "hosts", "pi", "AUTOFORMALIZE_LOOP_PROMPT.template.md"]

private def autoformalizeDoneWord : String :=
  "AFTK_LOOP_DONE"

private def autoformalizeContinueWord : String :=
  "AFTK_LOOP_CONTINUE"

private def autoformalizeLoopUsageText : String :=
  String.intercalate "\n" [
    "Usage:",
    "  lake run aftk_autoformalize_loop [options] <task ...>",
    "  lake run aftk_autoformalize_loop [options] --task-file <path>",
    "  lake run aftk_autoformalize_loop --help"
  ]

private def autoformalizeLoopHelpText : String :=
  String.intercalate "\n\n" [
    autoformalizeLoopUsageText,
    "Run pi in noninteractive print mode in a fresh stigmergic loop until the task is fully done.",
    String.intercalate "\n" [
      "Behavior:",
      s!"- each iteration runs `pi --print --no-session` in the current Lake workspace",
      s!"- it never uses `--continue`; each run must work from durable repo state",
      s!"- nonzero pi exit codes are treated as transient run errors and the loop continues",
      s!"- the loop stops only when the assistant's final nonempty line is exactly `{autoformalizeDoneWord}`",
      s!"- `{autoformalizeContinueWord}` and missing markers both cause another fresh iteration"
    ],
    String.intercalate "\n" [
      "Options:",
      "- --task-file <path>   Read the task text from a file",
      "- --max-steps <n>      Optional safety limit; if omitted, the loop is unbounded",
      "- --provider <name>    Forward pi provider selection",
      "- --model <pattern>    Forward pi model selection",
      "- --thinking <level>   Forward pi thinking level"
    ],
    String.intercalate "\n" [
      "Downstream-workspace behavior:",
      "- honors `AFTK_PI_COMMAND` when set; otherwise probes `pi` on PATH plus project-local / `aftk`-package-local installs and uses the newest runnable version",
      "- if `.pi/extensions/aftk-toolkit.ts` or `.pi/extensions/aftk-logging.ts` are missing, the script loads the AFTK extension entrypoints directly from the resolved `aftk` package",
      "- if `.pi/APPEND_SYSTEM.md` is missing, the script appends the package's AFTK agent-guidance template directly",
      "- logs and cost summaries still land under `.aftk/logs/` and `.aftk/cost/` via the logging extension"
    ]
  ]

private structure AutoformalizeLoopOptions where
  taskWordsRev : List String := []
  taskFile? : Option FilePath := none
  maxSteps? : Option Nat := none
  provider? : Option String := none
  model? : Option String := none
  thinking? : Option String := none

private def parsePositiveNatOption (flag value : String) : Except String Nat :=
  match value.toNat? with
  | some n =>
      if n > 0 then
        pure n
      else
        throw s!"Expected a positive integer for {flag}, got: {value}"
  | none =>
      throw s!"Expected a positive integer for {flag}, got: {value}"

private def parseAutoformalizeLoopArgs : List String → Except String AutoformalizeLoopOptions
  | [] =>
      pure {}
  | "--task-file" :: path :: rest => do
      let opts ← parseAutoformalizeLoopArgs rest
      match opts.taskFile? with
      | some _ => throw "--task-file may be specified at most once"
      | none => pure { opts with taskFile? := some (System.FilePath.mk path) }
  | "--max-steps" :: raw :: rest => do
      let maxSteps ← parsePositiveNatOption "--max-steps" raw
      let opts ← parseAutoformalizeLoopArgs rest
      match opts.maxSteps? with
      | some _ => throw "--max-steps may be specified at most once"
      | none => pure { opts with maxSteps? := some maxSteps }
  | "--provider" :: provider :: rest => do
      let opts ← parseAutoformalizeLoopArgs rest
      match opts.provider? with
      | some _ => throw "--provider may be specified at most once"
      | none => pure { opts with provider? := some provider }
  | "--model" :: model :: rest => do
      let opts ← parseAutoformalizeLoopArgs rest
      match opts.model? with
      | some _ => throw "--model may be specified at most once"
      | none => pure { opts with model? := some model }
  | "--thinking" :: thinking :: rest => do
      let opts ← parseAutoformalizeLoopArgs rest
      match opts.thinking? with
      | some _ => throw "--thinking may be specified at most once"
      | none => pure { opts with thinking? := some thinking }
  | arg :: rest => do
      if arg.startsWith "-" then
        throw s!"Unrecognized option: {arg}"
      let opts ← parseAutoformalizeLoopArgs rest
      pure { opts with taskWordsRev := arg :: opts.taskWordsRev }

private def stdoutPut (text : String) : IO Unit := do
  let stdout ← IO.getStdout
  stdout.putStr text
  stdout.flush

private def stderrPut (text : String) : IO Unit := do
  let stderr ← IO.getStderr
  stderr.putStr text
  stderr.flush

private def resolveAgainst (baseDir path : FilePath) : FilePath :=
  if path.isAbsolute then path else baseDir / path

private def autoformalizePromptTemplatePath (aftkDir : FilePath) : FilePath :=
  aftkDir / autoformalizeLoopPromptRelativePath

private def readAutoformalizePromptTemplate (aftkDir : FilePath) : IO String := do
  let path := autoformalizePromptTemplatePath aftkDir
  unless (← path.pathExists) do
    throw <| IO.userError s!"AFTK autoformalize loop failed: prompt template is missing: {path}"
  IO.FS.readFile path

private def resolveAutoformalizeTask (projectDir : FilePath) (opts : AutoformalizeLoopOptions) : IO String := do
  if !opts.taskWordsRev.isEmpty && opts.taskFile?.isSome then
    throw <| IO.userError "AFTK autoformalize loop failed: provide either free-form task words or --task-file, not both."
  match opts.taskFile? with
  | some taskFile =>
      let resolved := resolveAgainst projectDir taskFile
      unless (← resolved.pathExists) do
        throw <| IO.userError s!"AFTK autoformalize loop failed: task file is missing: {resolved}"
      let contents ← IO.FS.readFile resolved
      let trimmed := contents.trimAscii.toString
      if trimmed.isEmpty then
        throw <| IO.userError s!"AFTK autoformalize loop failed: task file is empty: {resolved}"
      pure trimmed
  | none =>
      let taskText := String.intercalate " " opts.taskWordsRev.reverse
      let trimmed := taskText.trimAscii.toString
      if !trimmed.isEmpty then
        pure trimmed
      else
        let entrypointPath := projectDir / "entrypoint.md"
        if ← entrypointPath.pathExists then
          pure "Work on the task described in `entrypoint.md` at the project root. Read that file first and then continue stigmergically from durable repo state."
        else
          throw <| IO.userError "AFTK autoformalize loop failed: no task was provided and no `entrypoint.md` exists in the project root."

private def buildAutoformalizeLoopPrompt (templateBody task : String) (step : Nat) : String :=
  String.intercalate "\n\n" [
    templateBody,
    String.intercalate "\n" [
      "## Task",
      task
    ],
    String.intercalate "\n" [
      "## Loop contract",
      s!"- This is fresh stigmergic iteration #{step}. Do not rely on any previous session, chat, or hidden queue state.",
      "- Inspect the current repo state directly; previous iterations may already have changed files or created durable coordination artifacts.",
      s!"- If and only if the whole task is complete in repo state at the end of this run, end the final nonempty line of your response with exactly `{autoformalizeDoneWord}`.",
      s!"- Otherwise end the final nonempty line of your response with exactly `{autoformalizeContinueWord}`.",
      "- Do not put punctuation, code fences, or extra words after the final marker line."
    ]
  ]

private def localPiBinaryName : String :=
  if System.Platform.isWindows then "pi.cmd" else "pi"

private structure ResolvedPiCommand where
  cmd : String
  source : String
  versionText? : Option String := none
  version? : Option (Nat × Nat × Nat) := none

private def parsePiVersion? (raw : String) : Option (Nat × Nat × Nat) :=
  match raw.trimAscii.toString |>.splitOn "." with
  | [major, minor, patch] =>
      match major.toNat?, minor.toNat?, patch.toNat? with
      | some major, some minor, some patch => some (major, minor, patch)
      | _, _, _ => none
  | _ => none

private def comparePiVersions (lhs rhs : Nat × Nat × Nat) : Ordering :=
  let (lhsMajor, lhsMinor, lhsPatch) := lhs
  let (rhsMajor, rhsMinor, rhsPatch) := rhs
  if lhsMajor < rhsMajor then .lt
  else if lhsMajor > rhsMajor then .gt
  else if lhsMinor < rhsMinor then .lt
  else if lhsMinor > rhsMinor then .gt
  else if lhsPatch < rhsPatch then .lt
  else if lhsPatch > rhsPatch then .gt
  else .eq

private def probePiCommand? (cmd source : String) (cwd : FilePath) : IO (Option ResolvedPiCommand) := do
  try
    let out ← IO.Process.output {
      cmd := cmd
      args := #["--version"]
      cwd := some cwd
    }
    if out.exitCode != 0 then
      return none
    let stdoutText := out.stdout.trimAscii.toString
    let stderrText := out.stderr.trimAscii.toString
    let versionText? :=
      if !stdoutText.isEmpty then some stdoutText
      else if !stderrText.isEmpty then some stderrText
      else none
    return some {
      cmd := cmd
      source := source
      versionText? := versionText?
      version? := versionText?.bind parsePiVersion?
    }
  catch _ =>
    return none

private def bestResolvedPiCommand? : List ResolvedPiCommand → Option ResolvedPiCommand
  | [] => none
  | head :: tail =>
      some <| tail.foldl (init := head) fun best candidate =>
        match candidate.version?, best.version? with
        | some candidateVersion, some bestVersion =>
            match comparePiVersions candidateVersion bestVersion with
            | .gt => candidate
            | .eq => best
            | .lt => best
        | some _, none => candidate
        | none, some _ => best
        | none, none => best

private def resolvePiCommand (projectDir aftkDir : FilePath) : IO ResolvedPiCommand := do
  let envOverride? ← IO.getEnv "AFTK_PI_COMMAND"
  let envOverride? := envOverride?.bind fun raw =>
    let trimmed := raw.trimAscii.toString
    if trimmed.isEmpty then none else some trimmed
  match envOverride? with
  | some cmd =>
      return {
        cmd := cmd
        source := "env:AFTK_PI_COMMAND"
      }
  | none =>
      let projectCandidate := projectDir / "node_modules" / ".bin" / localPiBinaryName
      let aftkCandidate := aftkDir / "node_modules" / ".bin" / localPiBinaryName
      let mut candidates : List (String × String) := [("pi", "PATH")]
      if ← projectCandidate.pathExists then
        candidates := candidates ++ [(projectCandidate.toString, "project-local")]
      if ← aftkCandidate.pathExists then
        let aftkCmd := aftkCandidate.toString
        unless candidates.any (fun (cmd, _) => cmd == aftkCmd) do
          candidates := candidates ++ [(aftkCmd, "aftk-package-local")]
      let mut resolvedRev : List ResolvedPiCommand := []
      for (cmd, source) in candidates do
        if let some resolved ← probePiCommand? cmd source projectDir then
          resolvedRev := resolved :: resolvedRev
      match bestResolvedPiCommand? resolvedRev.reverse with
      | some resolved =>
          pure resolved
      | none =>
          match candidates with
          | (cmd, source) :: _ => pure { cmd := cmd, source := source }
          | [] => pure { cmd := "pi", source := "PATH" }

private def verifyPiCommand (resolved : ResolvedPiCommand) (cwd : FilePath) : IO Unit := do
  try
    let out ← IO.Process.output {
      cmd := resolved.cmd
      args := #["--version"]
      cwd := some cwd
    }
    if out.exitCode != 0 then
      throw <| IO.userError s!"AFTK autoformalize loop failed: `pi --version` exited with code {out.exitCode}.\n{out.stderr}"
  catch e =>
    throw <| IO.userError s!"AFTK autoformalize loop failed: could not execute `pi` command `{resolved.cmd}` ({resolved.source}).\n{e.toString}"

private def appendArgPair (args : Array String) (flag : String) (value? : Option String) : Array String :=
  match value? with
  | some value => args.push flag |>.push value
  | none => args

private def configuredToolkitShimPath (projectDir : FilePath) : FilePath :=
  projectDir / ".pi" / "extensions" / "aftk-toolkit.ts"

private def configuredLoggingShimPath (projectDir : FilePath) : FilePath :=
  projectDir / ".pi" / "extensions" / "aftk-logging.ts"

private def configuredAppendSystemPath (projectDir : FilePath) : FilePath :=
  projectDir / ".pi" / "APPEND_SYSTEM.md"

private def missingAftkPiResourceArgs (projectDir aftkDir : FilePath) : IO (Array String) := do
  let mut args : Array String := #[]
  let toolkitShim := configuredToolkitShimPath projectDir
  let loggingShim := configuredLoggingShimPath projectDir
  let appendSystemPath := configuredAppendSystemPath projectDir
  if !(← toolkitShim.pathExists) then
    args := args.push "-e" |>.push (aftkDir / toolkitEntryRelativePath).toString
  if !(← loggingShim.pathExists) then
    args := args.push "-e" |>.push (aftkDir / loggingEntryRelativePath).toString
  if !(← appendSystemPath.pathExists) then
    args := args.push "--append-system-prompt" |>.push (promptTemplatePath aftkDir).toString
  pure args

private def lastNonemptyLineAux : List String → Option String
  | [] => none
  | line :: rest =>
      let trimmed := line.trimAscii.toString
      if trimmed.isEmpty then lastNonemptyLineAux rest else some trimmed

private def lastNonemptyLine? (text : String) : Option String :=
  lastNonemptyLineAux (text.splitOn "\n").reverse

private def doneMarker? (stdout : String) : Bool :=
  lastNonemptyLine? stdout == some autoformalizeDoneWord

private partial def runAutoformalizeLoopSteps
    (projectDir aftkDir : FilePath)
    (piCmd : String)
    (opts : AutoformalizeLoopOptions)
    (templateBody task : String)
    (sharedPiArgs : Array String)
    (step : Nat := 1) : IO UInt32 := do
  if let some maxSteps := opts.maxSteps? then
    if step > maxSteps then
      stderrPut s!"Reached --max-steps={maxSteps} without seeing `{autoformalizeDoneWord}`.\n"
      return 2
  stderrPut s!"\n==> aftk_autoformalize_loop iteration {step}\n"
  let prompt := buildAutoformalizeLoopPrompt templateBody task step
  let runArgs :=
    sharedPiArgs ++
    #["--print", "--no-session", prompt]
  let out ← IO.Process.output {
    cmd := piCmd
    args := runArgs
    cwd := some projectDir
  }
  if !out.stdout.isEmpty then
    stdoutPut out.stdout
    unless out.stdout.endsWith "\n" do
      stdoutPut "\n"
  if !out.stderr.isEmpty then
    stderrPut out.stderr
    unless out.stderr.endsWith "\n" do
      stderrPut "\n"
  if out.exitCode == 0 && doneMarker? out.stdout then
    stderrPut s!"Detected completion marker `{autoformalizeDoneWord}`. Stopping loop.\n"
    return 0
  if out.exitCode != 0 then
    stderrPut s!"pi exited with code {out.exitCode}; continuing with a fresh iteration.\n"
  else
    stderrPut s!"Completion marker not detected; continuing with a fresh iteration.\n"
  runAutoformalizeLoopSteps projectDir aftkDir piCmd opts templateBody task sharedPiArgs (step + 1)

script aftk_autoformalize_loop (args) do
  match args with
  | ["--help"] | ["-h"] =>
      IO.println autoformalizeLoopHelpText
      pure 0
  | _ =>
      try
        let opts ←
          match parseAutoformalizeLoopArgs args with
          | .ok opts => pure opts
          | .error err => throw <| IO.userError err
        let ws ← getWorkspace
        let projectDir := ws.dir
        let some aftkPkg ← findPackageByName? `aftk
          | throw <| IO.userError "AFTK autoformalize loop failed: package `aftk` was not found in the current Lake workspace."
        let task ← resolveAutoformalizeTask projectDir opts
        let templateBody ← readAutoformalizePromptTemplate aftkPkg.dir
        let piResolved ← resolvePiCommand projectDir aftkPkg.dir
        verifyPiCommand piResolved projectDir
        let sharedPiArgsBase ← missingAftkPiResourceArgs projectDir aftkPkg.dir
        let sharedPiArgs :=
          appendArgPair
            (appendArgPair
              (appendArgPair sharedPiArgsBase "--provider" opts.provider?)
              "--model" opts.model?)
            "--thinking" opts.thinking?
        stderrPut s!"Workspace root: {projectDir}\n"
        stderrPut s!"AFTK package: {aftkPkg.dir}\n"
        stderrPut s!"pi command: {piResolved.cmd}\n"
        stderrPut s!"pi source: {piResolved.source}\n"
        if let some versionText := piResolved.versionText? then
          stderrPut s!"pi version: {versionText}\n"
        stderrPut s!"Loop stop marker: {autoformalizeDoneWord}\n"
        let exitCode ← runAutoformalizeLoopSteps projectDir aftkPkg.dir piResolved.cmd opts templateBody task sharedPiArgs
        pure exitCode
      catch e =>
        IO.eprintln e.toString
        pure 1
