import Lake

open System Lake DSL

package aftk where
  testDriver := "aftk_test"
  version := v!"0.1.0"

require lean_worker from git "https://github.com/adamtopaz/lean_worker"@"main"

lean_lib AFTK

lean_lib AFTKTest

@[default_target] lean_exe aftk where
  root := `Main
  supportInterpreter := true

lean_exe aftk_server where
  root := `AFTK.Server.Main
  supportInterpreter := true

lean_exe aftk_file_worker where
  root := `AFTK.FileWorker.Main
  supportInterpreter := true

lean_exe aftk_knowledgebase_test where
  root := `AFTKTest.KnowledgeBase.Main
  supportInterpreter := true

lean_exe aftk_informal_test where
  root := `AFTKTest.Informal.Main
  supportInterpreter := true

lean_exe aftk_server_test where
  root := `AFTKTest.Server.Main
  supportInterpreter := true

lean_exe aftk_test where
  root := `AFTKTest.Main
  supportInterpreter := true

private def generatedByLine : String :=
  "Generated by `lake run aftk_setup`. Re-run to refresh."

private def shimHeader : String :=
  s!"// {generatedByLine}"

private def promptHeader : String :=
  s!"<!-- {generatedByLine} -->"

private def toolkitEntryRelativePath : FilePath :=
  mkFilePath ["src", "hosts", "pi", "extension.ts"]

private def loggingEntryRelativePath : FilePath :=
  mkFilePath ["src", "hosts", "pi", "logging-extension.ts"]

private def promptSourceRelativePath : FilePath :=
  mkFilePath ["src", "hosts", "pi", "APPEND_SYSTEM.template.md"]

private def usageText : String :=
  String.intercalate "\n" [
    "Usage:",
    "  lake run aftk_setup",
    "  lake run aftk_setup --help"
  ]

private def helpText : String :=
  String.intercalate "\n\n" [
    usageText,
    "Create or refresh the project-local pi extension shims and appended system prompt for AFTK.",
    String.intercalate "\n" [
      "This command reads from the resolved `aftk` package:",
      "- src/hosts/pi/extension.ts",
      "- src/hosts/pi/logging-extension.ts",
      "- src/hosts/pi/APPEND_SYSTEM.template.md"
    ],
    String.intercalate "\n" [
      "This command writes:",
      "- .pi/extensions/aftk-toolkit.ts",
      "- .pi/extensions/aftk-logging.ts",
      "- .pi/APPEND_SYSTEM.md"
    ],
    "It is safe to rerun. Existing files are updated only when they match the generated-file marker."
  ]

private def dropLeadingEmptyParts : List String → List String
  | "" :: rest => dropLeadingEmptyParts rest
  | rest => rest

private def commonPrefixLength : List String → List String → Nat
  | left :: leftRest, right :: rightRest =>
      if left == right then
        commonPrefixLength leftRest rightRest + 1
      else
        0
  | _, _ => 0

private structure PathPieces where
  root? : Option String
  parts : List String

private def looksLikeWindowsDrive (part : String) : Bool :=
  part.length == 2 && part.drop 1 == ":"

private def pathPieces (path : FilePath) : PathPieces :=
  let normalized := path.normalize
  let parts := normalized.components
  if normalized.isAbsolute then
    if System.Platform.isWindows then
      match parts with
      | drive :: rest =>
          if looksLikeWindowsDrive drive then
            { root? := some drive, parts := rest }
          else
            { root? := some (String.singleton FilePath.pathSeparator), parts := dropLeadingEmptyParts parts }
      | [] =>
          { root? := some (String.singleton FilePath.pathSeparator), parts := [] }
    else
      { root? := some "/", parts := dropLeadingEmptyParts parts }
  else
    { root? := none, parts := parts }

private def importPathText (path : FilePath) : String :=
  if System.Platform.isWindows then
    path.normalize.toString.map fun c => if c = '\\' then '/' else c
  else
    path.normalize.toString

private def absoluteImportSpecifier (path : FilePath) : String :=
  let text := importPathText path
  if path.isAbsolute then
    if System.Platform.isWindows then s!"file:///{text}" else s!"file://{text}"
  else if text.startsWith "." then
    text
  else
    s!"./{text}"

private def relativeImportSpecifier? (fromDir targetPath : FilePath) : Option String :=
  let fromPieces := pathPieces fromDir
  let destPieces := pathPieces targetPath
  if fromPieces.root? != destPieces.root? then
    none
  else
    let common := commonPrefixLength fromPieces.parts destPieces.parts
    let upParts := List.replicate (fromPieces.parts.length - common) ".."
    let downParts := destPieces.parts.drop common
    let relParts := upParts ++ downParts
    let relPath := mkFilePath relParts
    let relText := Lake.mkRelPathString relPath
    if relText.isEmpty then
      some "./"
    else if relText.startsWith "." then
      some relText
    else
      some s!"./{relText}"

private def computeImportSpecifier (fromFile targetPath : FilePath) : String :=
  match fromFile.parent with
  | some fromDir =>
      (relativeImportSpecifier? fromDir targetPath).getD (absoluteImportSpecifier targetPath)
  | none =>
      absoluteImportSpecifier targetPath

private def buildShimContent (importSpecifier : String) : String :=
  String.intercalate "\n" [
    shimHeader,
    "export { default } from \"" ++ importSpecifier ++ "\";",
    ""
  ]

private def promptTemplatePath (aftkDir : FilePath) : FilePath :=
  aftkDir / promptSourceRelativePath

private def buildPromptContent (sourcePath : FilePath) : IO String := do
  unless (← sourcePath.pathExists) do
    throw <| IO.userError s!"AFTK setup failed: expected appended system prompt template is missing: {sourcePath}"
  let body ← IO.FS.readFile sourcePath
  return promptHeader ++ "\n" ++ body

private inductive ManagedWritePlan where
  | create
  | overwrite
  | unchanged

private def classifyManagedWrite (path : FilePath) (content marker : String) : IO ManagedWritePlan := do
  if !(← path.pathExists) then
    return .create
  let current ← IO.FS.readFile path
  if current == content then
    return .unchanged
  if current.startsWith marker then
    return .overwrite
  throw <| IO.userError s!"Refusing to overwrite existing user-managed file: {path}"

private def applyManagedWrite (path : FilePath) (content : String) (plan : ManagedWritePlan) : IO Unit := do
  match plan with
  | .unchanged =>
      pure ()
  | .create | .overwrite =>
      Lake.createParentDirs path
      IO.FS.writeFile path content

private def actionLabel (plan : ManagedWritePlan) : String :=
  match plan with
  | .create => "installed"
  | .overwrite => "updated"
  | .unchanged => "already up to date"

private structure SetupSummary where
  projectDir : FilePath
  aftkDir : FilePath
  toolkitEntryFile : FilePath
  loggingEntryFile : FilePath
  promptSourcePath : FilePath
  toolkitShimPath : FilePath
  loggingShimPath : FilePath
  promptPath : FilePath
  toolkitImportSpecifier : String
  loggingImportSpecifier : String
  toolkitShimPlan : ManagedWritePlan
  loggingShimPlan : ManagedWritePlan
  promptPlan : ManagedWritePlan

private def runAftkSetup : ScriptM SetupSummary := do
  let ws ← getWorkspace
  let projectDir := ws.dir
  let some aftkPkg ← findPackageByName? `aftk
    | throw <| IO.userError "AFTK setup failed: package `aftk` was not found in the current Lake workspace."
  let toolkitEntryFile := aftkPkg.dir / toolkitEntryRelativePath
  unless (← toolkitEntryFile.pathExists) do
    throw <| IO.userError s!"AFTK setup failed: expected pi toolkit extension entrypoint is missing: {toolkitEntryFile}"
  let loggingEntryFile := aftkPkg.dir / loggingEntryRelativePath
  unless (← loggingEntryFile.pathExists) do
    throw <| IO.userError s!"AFTK setup failed: expected pi logging extension entrypoint is missing: {loggingEntryFile}"
  let promptSourcePath := promptTemplatePath aftkPkg.dir
  let toolkitShimPath := projectDir / ".pi" / "extensions" / "aftk-toolkit.ts"
  let loggingShimPath := projectDir / ".pi" / "extensions" / "aftk-logging.ts"
  let promptPath := projectDir / ".pi" / "APPEND_SYSTEM.md"
  let toolkitImportSpecifier := computeImportSpecifier toolkitShimPath toolkitEntryFile
  let loggingImportSpecifier := computeImportSpecifier loggingShimPath loggingEntryFile
  let toolkitShimContent := buildShimContent toolkitImportSpecifier
  let loggingShimContent := buildShimContent loggingImportSpecifier
  let promptContent ← buildPromptContent promptSourcePath
  let toolkitShimPlan ← classifyManagedWrite toolkitShimPath toolkitShimContent shimHeader
  let loggingShimPlan ← classifyManagedWrite loggingShimPath loggingShimContent shimHeader
  let promptPlan ← classifyManagedWrite promptPath promptContent promptHeader
  applyManagedWrite toolkitShimPath toolkitShimContent toolkitShimPlan
  applyManagedWrite loggingShimPath loggingShimContent loggingShimPlan
  applyManagedWrite promptPath promptContent promptPlan
  return {
    projectDir,
    aftkDir := aftkPkg.dir,
    toolkitEntryFile,
    loggingEntryFile,
    promptSourcePath,
    toolkitShimPath,
    loggingShimPath,
    promptPath,
    toolkitImportSpecifier,
    loggingImportSpecifier,
    toolkitShimPlan,
    loggingShimPlan,
    promptPlan,
  }

script aftk_setup (args) do
  match args with
  | [] =>
      try
        let summary ← runAftkSetup
        IO.println s!"Workspace root: {summary.projectDir}"
        IO.println s!"AFTK package: {summary.aftkDir}"
        IO.println s!"AFTK pi toolkit entrypoint: {summary.toolkitEntryFile}"
        IO.println s!"AFTK pi logging entrypoint: {summary.loggingEntryFile}"
        IO.println s!"AFTK prompt template: {summary.promptSourcePath}"
        IO.println s!"AFTK pi toolkit shim {actionLabel summary.toolkitShimPlan}: {summary.toolkitShimPath}"
        IO.println s!"AFTK pi logging shim {actionLabel summary.loggingShimPlan}: {summary.loggingShimPath}"
        IO.println s!"AFTK appended system prompt {actionLabel summary.promptPlan}: {summary.promptPath}"
        IO.println s!"Toolkit shim import specifier: {summary.toolkitImportSpecifier}"
        IO.println s!"Logging shim import specifier: {summary.loggingImportSpecifier}"
        IO.println "If pi is already running, use `/reload`."
        pure 0
      catch e =>
        IO.eprintln e.toString
        pure 1
  | ["--help"] | ["-h"] =>
      IO.println helpText
      pure 0
  | _ =>
      IO.eprintln usageText
      pure 2
