name = "aftk"
version = "0.1.0"
defaultTargets = ["aftk_server", "aftk_file_worker", "AFTK", "Informalize", "informalize", "tests"]

[[require]]
name = "lean_worker"
git = "https://github.com/adamtopaz/lean_worker"
rev = "main"

[[lean_lib]]
name = "AFTK"

[[lean_lib]]
name = "Informalize"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "aftk_file_worker"
root = "AFTK.FileWorker"
supportInterpreter = true

[[lean_exe]]
name = "aftk_server"
root = "AFTK.Server"
supportInterpreter = true

[[lean_exe]]
name = "informalize"
root = "InformalizeCli"
supportInterpreter = true

[[lean_exe]]
name = "tests"
root = "Tests"
